### PR TITLE
Formatted output + better error loggings from property tests

### LINKED ISSUE #11: Failed test output difficult to read when ExUnit running with `async: true`
Hello!

It would be nice if we could run tests asynchronously while keeping the debug information from failed tests readable.

Could we use a custom ExUnit formatter for this?

Cheers,
Louis

### PR DESCRIPTION
**Pull request by Primordus**
Fixes #11, currently error loggings are displayed all at once after all tests ran. This could possibly be improved by first monitoring the ExUnit test processes as soon as they emit one of the various "error" messages and then display the errors for that process as soon as the server process notices that a test process goes down.

### CODE REVIEW

**Comment by parroty** [comment]
Thanks, it's great! I'll be merging, but please allow me some-time to play around.

File: lib/excheck/io_server.ex [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+    {:noreply, new_state}
+  end
+  def handle_info({:io_request, from, ref, 
+                  {:put_chars, :unicode, msg}}, state) do
+    # Receive all IO requests here
+    new_state = handle_output(msg, [], from, state)
+    from |> send {:io_reply, ref, :ok}
+    {:noreply, new_state}
+  end
+  # TODO need more cases here to handle all forms of IO?
```
Comment (parroty) [inline lib/excheck/io_server.ex]: Do you have specific other messages which needs to be handled here? If there's any, it may be good to add fallback clause?

I was reading the following documents, but haven't been able to understand the possible list of them.  
- http://elixir-lang.org/getting-started/io-and-the-file-system.html#processes-and-group-leaders
- https://github.com/elixir-lang/elixir/blob/v1.1.1/lib/elixir/lib/io.ex#L1
    - The elixir's requests are just redirected to erlang's `:io.put_chars`?
- http://www.erlang.org/doc/apps/stdlib/io_protocol.html
    - "1.2  Output Requests" seems only notes "put_chars".

**Comment by parroty** [comment]
Thanks for the PR. I didn't know much about group_leader and IO framework, but it seems nice. I've added one comment to the TODO section, could you check?

File: lib/excheck/io_server.ex (hunk 1 above)
Comment (Primordus) [inline lib/excheck/io_server.ex]: The server itself doesn't expect any other kind of messages besides :io_request.

Top clause handles all output coming from triq (using io:format). Bottom clause handles Elixir output (for example using IO.write). The differences are that io:format uses a list of integers with interpolated values in a separate value list while Elixir uses (utf8) binaries that already contain the interpolated data. (e.g. "#{12345}"). It looks like Elixir only uses put_chars..

Should we support the input requests? (Seems rather useless in a test run but you never know..)
Not sure if this covers everything, for now I will add a fallback clause just to be safe (won't handle input requests). 

For a more complete solution, we might have to mimic something like this: https://github.com/erlang/otp/blob/1523be48ab4071b158412f4b06fe9c8d6ba3e73c/lib/kernel/src/user.erl#L182-#L291

**Comment by parroty** [comment]
Thanks!

**Comment by lpil** [comment]
Just wanted to comment saying that I'm really enjoying this new output! :D

**Comment by Primordus** [comment]
You're welcome! Was a lot of fun to make and learned a thing or 2 myself implementing this.. :smile:

**Comment by lpil** [comment]
Yes! I enjoyed reading the implementation. Didn't realise you could do that with output.
